website/auth.py
from flask import Blueprint, render_template, flash, redirect, send_from_directory, request
from werkzeug.utils import secure_filename

from .forms import LoginForm, SignUpForm, PasswordChangeForm, ProfilePhotoForm
from .models import Customer
from . import db
from flask_login import login_user, login_required, logout_user

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data

        customer = Customer.query.filter_by(email=email).first()

        if customer:
            if customer.verify_password(password=password):
                login_user(customer) # Зберігає ID користувача в сесії, Flask-Login запам'ятовує
                return redirect('/')
            else:
                flash('Invalid password!', 'danger')
        else:
            form.email.data = ''
            flash('Account does not exist. Please sign up.', 'danger')

    return render_template('login.html', form=form)


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    form = SignUpForm()
    if form.validate_on_submit():
        email = form.email.data
        username = form.username.data
        password1 = form.password1.data
        password2 = form.password2.data

        if password1 == password2:
            new_customer = Customer()
            new_customer.username = username
            new_customer.email = email
            new_customer.password = password2 # хешування паролю

            existing_email = Customer.query.filter_by(email=email).first()
            existing_username = Customer.query.filter_by(username=username).first()

            if existing_email:
                form.email.data = ''
                flash('This email is already registered. Try another one.', 'danger')
            if existing_username:
                form.username.data = ''
                flash('This username is already taken. Choose a different one.', 'danger')

            try:
                db.session.add(new_customer)
                db.session.commit()
                flash('Account created successfully! You can now log in.', 'success')
                return redirect('/login')
            except Exception as e:
                print(e)
                if not existing_email or not existing_username:
                    print('Something went wrong. Account not created.')

        else:
            flash('Passwords do not match. Please try again.', 'danger')

    return render_template('signup.html', form=form)

@auth.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect('/')

@auth.route('/profile_photo/<path:filename>')
def get_image(filename):
    return send_from_directory('../profile_photo', filename)

@auth.route('/profile/<int:customer_id>', methods=['GET', 'POST'])
@login_required
def profile(customer_id):
    customer_update_photo = Customer.query.get(customer_id)
    form = ProfilePhotoForm()

    if form.validate_on_submit():
       file = form.profile_pic.data
       file_name = secure_filename(file.filename)
       file_path = f'./profile_photo/{file_name}'
       file.save(file_path)

       try:
            Customer.query.filter_by(id=customer_id).update(dict(profile_pic = file_path))
            db.session.commit()
            return render_template('profile.html', customer=customer_update_photo, form=form)
       except Exception as e:
            print(e)
            flash('Profile picture is not updated!', 'danger')
    else:
        if request.method == "POST":
            flash('Profile picture is not updated!', 'danger')

    return render_template('profile.html', customer=customer_update_photo, form=form)

@auth.route('/change-password/<int:customer_id>', methods=['GET', 'POST'])
@login_required
def change_password(customer_id):
    form = PasswordChangeForm()
    customer = Customer.query.get(customer_id)

    if form.validate_on_submit():
        current_password = form.current_password.data
        new_password = form.new_password.data
        confirm_new_password = form.confirm_new_password.data

        if customer.verify_password(current_password):
            if new_password == confirm_new_password:
                customer.password = confirm_new_password
                db.session.commit()
                flash('Your password has been updated.', 'success')
                return redirect(f'/profile/{customer_id}')
            else:
                flash('Your new passwords do not match.', 'danger')
        else:
            flash('Invalid current password.', 'danger')

    return render_template('change_password.html', form=form)

website/templates/add_shop_items.html
{% extends 'base.html' %}

{% block title %} Add Shop Items {% endblock %}

{% block body %}

<form action="" method="POST" enctype="multipart/form-data">
    {{ form.hidden_tag() }}

    <table class="table table-dark table-hover">
        <tr>
            <th>{{ form.product_name.label }}</th>
            <th>{{ form.previous_price.label }} (UAH)</th>
            <th>Current price (UAH)</th>
            <th>{{ form.in_stock.label }}</th>
            <th>Categories</th>
            <th>{{ form.product_description.label }}</th>
            <th>Picture</th>
        </tr>

        <tr>
            <td>{{ form.product_name }}</td>
            <td>{{ form.previous_price(style="max-width: 180px") }}</td>
            <td>{{ form.current_price(style="max-width: 180px") }}</td>
            <td>{{ form.in_stock(style="max-width: 140px") }}</td>
            <td>{{ form.categories }}</td>
            <td>
                {{ form.product_description }}
            </td>

            <td>{{ form.product_picture(style="max-width: 270px") }}</td>
        </tr>
    </table>

    <div class="d-flex justify-content-end">
        {{ form.add_product() }}
    </div>
</form>

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/ae4427d25b.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.11.3/font/bootstrap-icons.min.css" integrity="sha512-dPXYcDub/aeb08c63jRq/k6GaKccl256JQy/AnOq7CAnEZ9FzSL9wSbcZkMp4R26vBsMLFYH4kQ67/bbV8XaCQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="{{ url_for('static', filename='css/all.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/profile.css') }}">

    <title> Amazon | {% block title %} {% endblock %} </title>
</head>

<nav class="navbar navbar-expand-lg" style="background-color: white;">
      <div class="container-fluid">
        <a class="navbar-brand" href="#" style="color: orange; font-size: 30px; margin-right: -2px;">
          <i class="fa-brands fa-amazon"></i>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/" style="font-family: cursive; font-size: 19px;">Amazon</a>
            </li>

          </ul>

          <form class="d-flex" role="search" action="/search" style="margin-right: 170px;" method="POST">
            <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search">
            <button class="btn" type="submit">Search</button>
          </form>
        </div>

           <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item mx-2" id="items">

            {% if current_user.id != 1 %}
                 {% if cart | length < 1 %}
                    <a class="nav-link text-grey" href="/cart"><span class="badge bg-success"></span> Cart
                       <i class="fa-solid fa-cart-shopping"></i>
                    </a>
                 {% else %}
                     <a class="nav-link text-grey" href="/cart"><span class="badge bg-success"></span> Cart
                        <i class="bi bi-{{ cart | length }}-square-fill"></i>
                    </a>
                 {% endif %}
            {% else %}
                <a class="nav-link text-grey" href="/shop-items"><span class="badge bg-success"></span> Shop Items
                    <i class="fa-solid fa-cart-shopping"></i>
                </a>
            {% endif %}

            </li>

           <li class="nav-item dropdown mx-2">
            <a class="nav-link dropdown-toggle text-grey" href="#" role="button" id="profileDropdown" data-bs-toggle="dropdown" aria-hidden="false">
             Account
            </a>
           <ul class="dropdown-menu" aria-labelledby="profileDropdown">

             {% if current_user.is_authenticated %}
                <li><a class="dropdown-item" href="/profile/{{ current_user.id }}">Profile <i class="fa-solid fa-user"></i></a></li>

                {% if current_user.id == 1 %}
                    <li><a class="dropdown-item" href="/view-orders">Orders <i class="fa-solid fa-truck-fast"></i></a></li>
                {% else %}
                    <li><a class="dropdown-item" href="/orders">Orders <i class="fa-solid fa-truck-fast"></i></a></li>
                {% endif %}

                <li><a class="dropdown-item" href="/logout">Log Out <i class="fa-solid fa-right-from-bracket"></i></a></li>
             {% else %}
                <li><a class="dropdown-item" href="/login">Login <i class="fa-solid fa-right-to-bracket"></i></a></li>
             {% endif %}

           </ul>
          </li>
        </ul>
      </div>
</nav>

 {% for message in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{ message[0] }} alert-dismissible fade show" role="alert" style="margin-top: 5px;">
        <strong>{{ message[1] }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

      {% if form.errors %}
                {% for field, errors in form.errors.items() %}
                   {% for error in errors %}
                         <li>{{ field }}: {{ error }}</li>
                   {% endfor %}
                {% endfor %}
      {% endif %}

    </div>
{% endfor %}

    {% block body %}

    {% endblock %}

    <footer class="container-fluid  text-center p-2 mt-5" style="background-color: orange; color: white;">
      <a style="color: white;">Amazon</a> | <span>
        <i class="fa-sharp fa-regular fa-copyright"></i></span> 2025 All rights reserved
    </footer>

    <script src="{{ url_for( 'static', filename='js/owl.carousel.min.js') }}"></script>
    <script src="{{ url_for( 'static', filename='js/all.min.js') }}"></script>
    <script src="{{ url_for( 'static', filename='js/jquery.js') }}"></script>
    <script src="{{ url_for( 'static', filename='js/myScript.js') }}"></script>

</html>

website/templates/change_password.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}


{% block body %}

<div class="col-sm-5 offset-sm-3" style="background-color: white; border-radius: 10px; margin-top: 51px; margin-left: 440px">

    <form style="padding: 30px;" method="POST">
    
        {{ form.hidden_tag() }}

        <div class="mb-3">
            <label for="exampleInputEmail" class="form-label"> {{ form.current_password.label }}</label>
            {{ form.current_password }}
        </div>

        <div class="mb-3">
            <label for="exampleInputEmail" class="form-label"> {{ form.new_password.label }}</label>
            {{ form.new_password }}
        </div>

        <div class="mb-3">
            <label for="exampleInputEmail" class="form-label"> {{ form.confirm_new_password.label }}</label>
            {{ form.confirm_new_password }}
        </div>

        {{ form.change_password }}
    
    </form>

</div>

{% endblock %}

website/templates/customers.html
{% extends 'base.html' %}

{% block title %} Customers {% endblock %}

{% block body %}

<table class="table table-bordered table-dark table-hover">
    <thead>
        <tr>
{#            <th scope="col">Customer ID</th>#}
            <th scope="col">Username</th>
            <th scope="col">Email</th>
            <th scope="col">Date Joined</th>
            <th scope="col">Delete Customer</th>
        </tr>
    </thead>

    <tbody>
        {% for customer in customers %}
            {% if customer.id != 1 %}
            <tr>
{#               <td>{{ customer.id }}</td>#}
               <td>{{ customer.username }}</td>
               <td>{{ customer.email }}</td>
               <td>{{ customer.date_joined.strftime("%d/%m/%Y, %H:%M:%S") }}</td>
               <td>
                <a href="/delete-customer/{{ customer.id }}">Delete</a>
               </td>
            </tr>
            {% endif %}

        {% endfor %}
    </tbody>
</table>

{% endblock %}

website/templates/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block body %}

<div class="container text-center">
    <div class="row m-3">

      <div class="col" style="margin: 3px;">

        <div class="list-group" id="right1"> {# aria-hidden - щоб РІДЕР не читав класи, а тільки текст - Супермаркет #}

            {% set icons = {
                'Supermarket': 'fa fa-shopping-basket',
                'Health & Beauty': 'fa fa-user',
                'Home & Office': 'fa-solid fa-comment',
                'Fashion': 'fa fa-camera',
                'Electronics': 'fa fa-audio-description',
                'Gaming': 'fa fa-cubes',
                'Baby Products': 'fa fa-child',
                'Sporting Goods': 'fa fa-bicycle',
                'Garden & Outdoor': 'fa fa-binoculars'
            } %}

            {% for category in categories %}
            <a href="/categories/{{ category.id }}" class="list-group-item list-group-item-action">
                <i class="{{ icons.get(category.category_name) }}" aria-hidden="true"></i> {{ category.category_name }}
            </a>

            {% endfor %}
        </div>

      </div>


      <div class="col-md-7" style="margin: 3px;">
        <img src="../static/images/onCenter2.gif" alt="" style="width: 600px; height: 365px; border-radius: 10px;">
      </div>

      <div class="col-md-2" style="margin: 3px">
          <div class="row">
            <div class="col">
                <img src="../static/images/saveOperation.gif" alt="" class="right2">
            </div>
          </div>

          <div class="row" style="margin-top: 12px;">
            <div class="col">
                <img src="../static/images/HappyAmazon.gif" alt="" class="right2">
            </div>
          </div>
      </div>

    </div>
</div>


<div class="container text-center">
    <div class="row" style="margin: 8px;">
        <div class="col" style="display: flex; background-color: white; border-radius: 10px; padding: 7px; margin: 5px;">
            <img src="../static/images/FreeDelivery.png" style="width: 30px; height: 30px;" alt="">
            <h6 style="margin: 4px">Various Categories</h6>
        </div>
        <div class="col" style="display: flex; background-color: white; border-radius: 10px; padding: 7px; margin: 5px;">
            <img src="../static/images/food.png" style="width: 30px; height: 30px;" alt="">
            <h6 style="margin: 4px">Amazon Food</h6>
        </div>
        <div class="col" style="display: flex; background-color: white; border-radius: 10px; padding: 7px; margin: 5px;">
            <img src="../static/images/airtime.png" style="width: 30px; height: 30px;" alt="">
            <h6 style="margin: 4px">Quick Transaction</h6>
        </div>
    </div>
</div>


<div class="container text-center">
    <div class="row" style="margin: 8px; background-color: rgb(219, 218, 218);" id="column">

        {% for item in items %}

        {% if item.in_stock > 0 %}
        <div class="col position-relative p-3" style="background-color: white;">

            <img src="{{ item.product_picture }}" alt="Photo of {{ item.product_picture }}" style="height: 212px; width: auto; border-radius: 10px;">

            <button class="btn position-absolute top-0 end-0" data-bs-toggle="modal" data-bs-target="#modal{{ item.id }}">
                <i class="fa-solid fa-circle-info"></i>
            </button>

            <div class="row" style="margin-top: 5px;">
                <h6 style="color: gray;"> {{ item.product_name }} </h6>
            </div>

            <div class="row" style="margin-top: 10px;">
                <div class="col">
                    <h5 style="font-weight: 600; font-family: 'Times New Roman', Times, serif;">{{ item.current_price }} UAH</h5>
                    {% if item.previous_price|float > item.current_price %}
                        <strike><p style="color: gray;"> {{ item.previous_price }} UAH</p></strike>
                    {% endif %}
                </div>

                <div class="col">
                    {% if current_user.id != 1 %}
                        <a href="/add-to-cart/{{ item.id }}">Add</a>
                    {% else %}
                        <a>Add</a>
                    {% endif %}

                    {% if item.previous_price|float > item.current_price %}
                         <h5 style="color: red; margin-top: 15px"> -{{ item.discount }}%</h5>
                    {% endif %}
                </div>
            </div>

            <div class="row">
                <p>{{ item.in_stock }} items left</p>
            </div>
        </div>

        {% else %}
         <div class="col position-relative p-3" style="background-color: white; filter: grayscale(100%);">
            <img src="{{ item.product_picture }}" alt="Photo of {{ item.product_picture }}" style="height: 212px; width: auto; border-radius: 10px;">

            <button class="btn position-absolute top-0 end-0" data-bs-toggle="modal" data-bs-target="#modal{{ item.id }}">
                <i class="fa-solid fa-circle-info"></i>
            </button>

            <div class="row" style="margin-top: 5px;">
                 <h6 style="color: gray;"> {{ item.product_name }} </h6>
            </div>

            <div class="row" style="margin-top: 10px;">
                <div class="col">
                    <h5 style="font-weight: 600; font-family: 'Times New Roman', Times, serif;  color: gray;">{{ item.current_price }} UAH</h5>
                    {% if item.previous_price|float > item.current_price %}
                        <strike><p style="color: gray;"> {{ item.previous_price }} UAH</p></strike>
                    {% endif %}
                </div>

                <div class="col">
                    {% if item.previous_price|float > item.current_price %}
                         <h5 style="color: gray; margin-top: 15px"> -{{ item.discount }}%</h5>
                    {% endif %}
                </div>
            </div>

            <div class="row">
                <strong>Not in stock</strong>
            </div>
        </div>
        {% endif %}

        {% endfor %}

    </div>

{% for item in items %}
    <div class="modal fade" id="modal{{ item.id }}" tabindex="-1" aria-labelledby="modalLabel{{ item.id }}" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">

                    <div class="modal-header">
                        <h5 class="modal-title" id="modalLabel{{ item.id }}">{{ item.product_name }}</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>

                    <div class="modal-body">
                        <p style="text-align: justify">{{ item.product_description }}</p>
                    </div>

                </div>
            </div>
        </div>
{% endfor %}

</div>

{% endblock %}

website/templates/login.html
{% extends 'forms.html' %}

{% block title %} Login {% endblock %}

{% block body %}

<section class="base" id="base-signup">
   <div class="base-content">
      <div class="form">

            <h3>
                Log in to start <br> shopping
            </h3>

            <hr class="first"> {# first horizontal line #}
            <form method="POST">
                {{ form.hidden_tag() }}

                <div class="email"> <h4>Email address</h4>{{ form.email }} <hr> </div>
                <div class="password"> <h4>Password</h4>{{ form.password }} <hr> </div>

                <div class="buttons">
                    <a href="/sign-up">Sign up</a>
                    {{ form.submit() }} {# <input type="submit" value="Log in"> #}
                </div>
            </form>

      </div>
   </div>
</section>

{% endblock %}

website/templates/order_update.html
{% extends 'base.html' %}

{% block title %} Update Order {% endblock %}


{% block body %}

<table class="table table-dark table-bordered table-hover">
    <thead>
        <tr>
            <th scope="col">Order Status</th>
            <th scope="col">Update Status</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <form action="" method="POST" enctype="multipart/form-data">
                {{ form.hidden_tag() }}

                <td>{{ form.order_status }}</td>
                <td>{{ form.update() }}</td>
            </form>
        </tr>
    </tbody>
</table>

{% endblock %}

website/templates/orders.html
{% extends 'base.html' %}

{% block title %} Orders {% endblock %}

{% block body %}

<div class="container my-5">

    <div class="row">
        {% if orders %}

        <h1 class="text-center mb-5" style="color: white;"> My Orders</h1>
        <div class="col-sm-13">
            <div class="card">
                <div class="card-body">

                    {% for item in orders %}

                    <div class="row">
                        <div class="col-sm-3 text-center align-self-center">
                            <img src="{{ item.product.product_picture }}" alt="" class="img-fluid img-thumbnail shadow-sm" height="150px" width="150px">
                        </div>
                        <div class="col-sm-7">
                            
                            <h3>{{ item.product.product_name }}</h3>
                            <p class="mb-2 text-muted small">Quantity: {{ item.quantity }}</p>
                            <p class="mb-2 text-muted small">Price: {{ item.price }} UAH</p>
                               
                                
                            <div class="col-sm-4">
                                <p>Order Status: {{ item.status }}</p>
                                {% if item.status == 'Pending' %}
                                <div class="progress">
                                    <div class="progress-bar" role="progressbar" style="width: 20%;"  aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>

                                {% elif item.status == 'Accepted' %}
                                <div class="progress">
                                    <div class="progress-bar bg-info" role="progressbar" style="width: 40%;"  aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>

                                {% elif item.status == 'Out for delivery' %}
                                <div class="progress">
                                    <div class="progress-bar bg-warning" role="progressbar" style="width: 70%;"  aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>

                                {% elif item.status == 'Delivered' %}
                                <div class="progress">
                                    <div class="progress-bar bg-success" role="progressbar" style="width: 100%;"  aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>

                                {% elif item.status == 'Canceled' %}
                                <div class="progress">
                                    <div class="progress-bar bg-danger" role="progressbar" style="width: 100%;"  aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                {% endif %}
                            </div>

                        </div>
                    </div>
                    <hr class="text-muted">
                    {% endfor %}
                </div>
            </div>
        </div>

        {% else %}
        <h1 class="text-center mb-5" style="color: white;">You have no orders</h1>

        {% endif %}
    </div>

</div>

{% endblock %}

website/templates/profile.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block body %}

<div class="container my-5">
    <div class="row align-items-start">

        <div class="col-md-3 border-end pe-4">
            <h3 class="text-white">Welcome, <span class="text-capitalize">{{ customer.username }}</span></h3>
            <ul class="list-unstyled mt-3">
                {% if current_user.id == 1 %}
                    <li class="d-grid"><a href="/customers" class="btn btn-primary">View Customers <i class="fa-solid fa-user"></i> </a></li>
                    <li class="d-grid"><a href="/view-orders" class="btn btn-primary mt-2">View Orders <i class="fa-solid fa-truck-fast"></i> </a></li>
                    <li class="d-grid"><a href="/shop-items" class="btn btn-primary mt-2">Edit Shop Items <i class="fa-solid fa-cart-shopping"></i> </a></li>
                    <li class="d-grid"><a href="/add-shop-items" class="btn btn-primary mt-2">Add Shop Items <i class="fa-solid fa-cart-shopping"></i> </a></li>
                {% endif %}

                <li class="d-grid"><a href="/change-password/{{ customer.id }}" class="btn btn-info mt-2">Change Password</a></li>

                {% if current_user.id != 1 %}
                    <li class="d-grid"><a href="/" class="btn btn-info mt-2">View Items</a></li>
                    <li class="d-grid"><a href="/orders" class="btn btn-info mt-2">View Orders</a></li>
                {% endif %}
            </ul>
        </div>

        <div class="col-md-9">
            <div class="row justify-content-center">
                <div class="col-md-10 p-4 shadow-lg rounded bg-white">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="card p-3 border-0">
                                <h4 class="text-primary"><i class="bi bi-person-circle"></i> Username: {{ customer.username }}</h4>
                                <p><i class="bi bi-envelope"></i> Email: {{ customer.email }}</p>
                                <p><i class="bi bi-calendar-check"></i> Account created: {{ customer.date_joined.strftime('%d %B %Y') }}</p>
                            </div>
                        </div>

                        <div class="col-md-4 text-center">
                            <img src="{{ url_for('auth.get_image', filename=customer.profile_pic.split('/')[-1]) }}" alt="Profile Picture"  class="avatar mt-2 rounded-circle shadow" style="width: 120px; height: 120px; object-fit: cover;">

                            <form action="" method="POST" enctype="multipart/form-data">
                                 {{ form.hidden_tag() }}
                                 <td>{{ form.profile_pic(style="width: 250px; margin-top: 11px") }}</td>
                                 <td>{{ form.update_picture(style="margin-top: 6px") }}</td>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock %}

website/templates/shop_items.html
{% extends 'base.html' %}

{% block title %} Shop items {% endblock %}

{% block body %}

{# Jinja2 – це шаблонний движок (template engine) для Python. Тобто код пайтон в HTML.
   = len(items) < 1 #}
{% if items | length < 1 %}
<h3 style="color: white;">No shop items</h3>

{% else %}

<style>
    .item-zero td{
        color: #ff6666;
    }
</style>

{#    tr - table row, th - table header, td - table data
      table-hover = коли наводиш курсор, то рядок підсвічується#}
<table class="table table-dark table-bordered table-hover">
        <tr>
            <th>Date added</th>
            <th>Product name</th>
            <th>Previous price (UAH)</th>
            <th>Current price (UAH)</th>
            <th>In stock</th>
            <th>Categories</th>
            <th>Product description</th>
            <th>Product picture</th>
            <th>Action</th>
        </tr>

        {% for item in items %}
        <tr class="{% if item.in_stock == 0 %}
                   item-zero
                   {% endif %}">

            <td>{{ item.date_added.strftime("%d/%m/%Y, %H:%M:%S") }}</td>
            <td>{{ item.product_name }}</td>
            <td>{{ item.previous_price }}</td>
            <td>{{ item.current_price }}</td>
            <td>{{ item.in_stock }}</td>

            <td>
               <ul>
                 {% for category in item.categories %}
                    <li>{{ category.category_name }}</li>
                 {% endfor %}
               </ul>
            </td>

            <td style="max-width: 300px">
                <p style="text-align: justify">{{ item.product_description[:50] }}
                    <span id="dots{{ item.id }}">...</span>
                    <span id="more{{ item.id }}" style="display: none"> {{ item.product_description[50:] }}</span>
                </p>
            <button onclick="myFunction('{{ item.id }}')" id="myBtn{{ item.id }}">Read more</button>
            </td>

            {% if item.in_stock < 1 %}
            <td><img src="{{ item.product_picture }}" alt="{{ item.product_name }} photo" style="filter: grayscale(100%); height: 50px; width: 50px; border-radius: 2px;"></td>
            {% else %}
            <td><img src="{{ item.product_picture }}" alt="{{ item.product_name }} photo" style="height: 50px; width: 50px; border-radius: 2px;"></td>
            {% endif %}

            <td>
                <a href="/update-item/{{ item.id }}">Update</a>
                <br>
                <a href="/delete-item/{{ item.id }}">Delete</a>
            </td>
        </tr>
        {% endfor %}

</table>

{% endif %}

{% endblock %}